export const PEPTIDES = [
  "5-Amino-1MQ",
  "ACE-031",
  "AICAR",
  "Adamax",
  "Adipotide",
  "AHK-Cu",
  "Alprostadil",
  "AOD-9604",
  "AOD-9605",
  "AOD-9606",
  "Ara-290",
  "B7-33",
  "Botulinum Toxin",
  "BPC-157",
  "BPC-157 + GHK-Cu + TB-500",
  "BPC-157 + TB-500 (2mg each)",
  "BPC-157 + TB-500 (5mg each)",
  "BPC-157 + TB-500 (10mg each)",
  "Bronchogen",
  "Cagrilintide",
  "Cagrilintide + Semaglutide",
  "Cardiogen",
  "Cartalax",
  "Cerebrolysin",
  "Chonluten",
  "CJC-1295 (with DAC)",
  "CJC-1295 (without DAC)",
  "CJC-1295 (without DAC) + Ipamorelin",
  "Cortagen",
  "Crystagen",
  "Dermorphin",
  "DSIP",
  "Epitalon",
  "EPO",
  "Follistatin",
  "FOXO4-DRI",
  "GHK-Cu",
  "GHRP-2",
  "GHRP-6",
  "GLP-1",
  "Glutathione",
  "Gonadorelin",
  "HCG",
  "Hexarelin",
  "HGH 191AA (Somatropin)",
  "HGH Fragment 176-191",
  "HMG",
  "Humanin",
  "Hyaluronic Acid",
  "IGF-1 DES",
  "IGF-1 LR3",
  "IGF-1 LR4",
  "Insulin",
  "Ipamorelin",
  "KissPeptin-10",
  "KPV",
  "Livagen",
  "LL-37",
  "Mazdutide",
  "Melatonin",
  "MGF",
  "MOTS-c",
  "MT-1 (Melanotan 1)",
  "MT-2 (Melanotan 2)",
  "N-Acetyl Epitalon Amidate",
  "NAD+",
  "Ovagen",
  "Oxytocin",
  "P21",
  "Pancragen",
  "PE 22-28",
  "PEG-MGF",
  "Pinealon",
  "PNC-27",
  "Prostamax",
  "PT-141",
  "PT-414",
  "Retatrutide",
  "Retatrutide + Cagrilintide",
  "Selank",
  "Semaglutide",
  "Semax",
  "Sermorelin",
  "SLU-PP-332",
  "Snap-8",
  "SS-31",
  "Survodutide",
  "TB-500",
  "TB-500 Fragment",
  "Teriparatide",
  "Tesamorelin",
  "Testagen",
  "Thymalin",
  "Thymosin Alpha-1",
  "Tirzepatide",
  "Vesugen",
  "VIP",
  "Vilon",
];

export const FREQUENCIES: { label: string; dosesPerWeek: number }[] = [
  { label: "Once daily", dosesPerWeek: 7 },
  { label: "Twice daily", dosesPerWeek: 14 },
  { label: "Every other day (EOD)", dosesPerWeek: 3.5 },
  { label: "3× per week", dosesPerWeek: 3 },
  { label: "Twice weekly", dosesPerWeek: 2 },
  { label: "Once weekly", dosesPerWeek: 1 },
  { label: "Twice monthly", dosesPerWeek: 0.5 },
  { label: "Once monthly", dosesPerWeek: 0.25 },
];

export const SYRINGE_UNITS: Record<string, number> = {
  "U-100": 100,
  "U-50": 50,
  "U-40": 40,
};
