export const PEPTIDES = [
  "5-amino-1MQ",
  "AOD-9604",
  "B7-33",
  "BPC-157",
  "Bronchogen",
  "Cardiogen",
  "Cartalax",
  "Cerebrolysin",
  "Chonluten",
  "CJC-1295 / Ipamorelin",
  "Cortagen",
  "Crystagen",
  "Epitalon",
  "FOX04-DRI",
  "GHK-Cu",
  "Glutathione",
  "HGH",
  "Humanin",
  "IGF-1 LR3",
  "KPV",
  "Livagen",
  "LL-37",
  "Melanotan 2 (MT2)",
  "MOTS-c",
  "NAD+",
  "Ovagen",
  "Oxytocin",
  "P21",
  "Pancragen",
  "Pinealon",
  "Prostamax",
  "PT-141",
  "Retatrutide",
  "Selank",
  "Semaglutide",
  "Semax",
  "SLU-PP-332",
  "SS-31",
  "TB-500",
  "Teriparatide",
  "Tesamorelin",
  "Testagen",
  "Thymalin",
  "Thymosin Alpha-1",
  "Tirzepatide",
  "Vesugen",
  "Vilon",
];

export const FREQUENCIES: { label: string; dosesPerWeek: number }[] = [
  { label: "Once daily", dosesPerWeek: 7 },
  { label: "Twice daily", dosesPerWeek: 14 },
  { label: "Every other day (EOD)", dosesPerWeek: 3.5 },
  { label: "3× per week", dosesPerWeek: 3 },
  { label: "Twice weekly", dosesPerWeek: 2 },
  { label: "Once weekly", dosesPerWeek: 1 },
  { label: "Twice monthly", dosesPerWeek: 0.5 },
  { label: "Once monthly", dosesPerWeek: 0.25 },
];

export const SYRINGE_UNITS: Record<string, number> = {
  "U-100": 100,
  "U-50": 50,
  "U-40": 40,
};
